version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: monitoring_service_db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=monitoring_service
    ports:
      - "5435:5432"
    restart: unless-stopped