package ru.erma.mappers;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;
import ru.erma.dto.ReadingRequest;
import ru.erma.model.Reading;

/**
 * The ReadingMapper interface is used to map between ReadingRequest DTOs and Reading entities.
 * It uses the MapStruct library to generate the implementation of the mapping methods.
 * It contains a method to map from a ReadingRequest to a Reading.
 */
@Mapper
public interface ReadingMapper {

    /**
     * The INSTANCE field is a singleton instance of the ReadingMapper.
     * It is obtained using the MapStruct factory method getMapper.
     */
    ReadingMapper INSTANCE = Mappers.getMapper(ReadingMapper.class);

    /**
     * This method is used to map from a ReadingRequest DTO to a Reading entity.
     * The implementation of this method is generated by MapStruct.
     *
     * @param readingRequest the ReadingRequest DTO to be mapped to a Reading entity
     * @return the Reading entity mapped from the ReadingRequest DTO
     */
    Reading toReading(ReadingRequest readingRequest);
}